### ISSUE TITLE
Trying the first example to see how it works, received this error

### ISSUE THREAD

**Issue by ktfth** [featherscloud/pinion#60]
### Steps to reproduce

Oh no! Something went wrong: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

### Expected behavior
Create a readme.md file

### Actual behavior
Trying the main example, have received this on windows: Oh no! Something went wrong: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

### System configuration

Tell us about the applicable parts of your setup.

**NodeJS version**:
v21.6.1

**Operating System**:
Windows 11

**Module Loader**:
ESM

**Comment by daffl** [comment]
Thank you for reporting! Can you see if you have version 0.5.1 (or later) installed? I believe this should be fixed via https://github.com/featherscloud/pinion/pull/59.

**Comment by daffl** [comment]
Looking at it again, that change didn't actually apply everywhere it needed to but it should work in v0.5.2 via #61 now.
